<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="SkiaSharp" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Android" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.NativeAssets.WebAssembly" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="3.119.4" />
    <PackageVersion Include="Svg.Skia" Version="4.9.1" />
    <PackageVersion Include="TUnit" Version="1.72.4" />
  </ItemGroup>
</Project>
