<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="SkiaSharp" Version="3.116.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="3.116.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.116.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="3.116.1" />
    <PackageVersion Include="TUnit" Version="1.68.17" />
  </ItemGroup>
</Project>
